[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
solc_version = "0.8.24"

remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
# ways to open access to filesystem. First is very generic and should be avoided.  
ffi = true
# fs.permissions =[{access = "read", path = "./img/"}] 

[fuzz]
runs = 64
depth = 32
fail_on_revert = true 

[invariant] 
runs = 16 
depth = 16 
fail_on_revert = false 
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
